# -*- coding: utf-8 -*-
"""Prokom 5-16-2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGBIjGEKygvjVDqD-WBLe10ZHEaLHSzK
"""

#For Loop
for a in range(10):
    print(a)



#While
n = 10
while n > 0:
    print(n)
    n = n - 2

#List
random = [3,6,7,2]
print(random[1:])

random = [3,6,7,2]
random.append(10)
random.append(9)
random.append(0)
print(random)

random = [3,6,7,2]
random[3] = 5
print(random)

random = [3,6,7,2]
x = 0
for i in random:
    random[x] = random[x] + 2
    x = x + 1
print(random)

# Function
def kirim_pesan(isi_pesan):
    print("Isi pesan:", isi_pesan)

# kirim_pesan("Selamat pagi")
# kirim_pesan("Hallo, apa kabar?")

def volume_tabung(r,t):
    v_t = 3.14 * r**2 * t
    print(v_t)

volume_tabung(6,5)
volume_tabung(8,4)

#Soal
# 10 + 9 + 8 + 7 + .... + 1 = 55
n = int(input())
a = n
while n > 0:
    a = a + (n-1)
    n = n - 1
    print(n)
print(a)

#Penyelesaian2
def Sum(n):
    if n <= 0:
        return n
    else:
        n = n + Sum(n-1)
        return n
Sum(10)

##oop
#Class Hewan
class Hewan:
    def __init__(self, nama, jenis, tinggal, jmlKaki):
        self.namaHwn = nama
        self.jenisHwn = jenis
        self.tinggalHwn = tinggal
        self.jmlKaki = jmlKaki

    def berlari(self, cara_lari):
        print(self.namaHwn,"",cara_lari,"di", self.tinggalHwn)

kucing = Hewan("Verry", "Mamalia", "Darat", 4)
hiu = Hewan("Doni", "Mamalia", "Laut", 0)
kucing.berlari("melompat")
hiu.berlari("terbang")


#Class Kalkulator
class Kalkulator:
    def __init__(self, angka1, angka2):
        self.angka01 = angka1
        self.angka02 = angka2

    def penjumlahan(self):
        jumlah = self.angka01 + self.angka02
        print(jumlah)

    def perkalian(self):
        kali = self.angka01 * self.angka02
        print(kali)

    def pembagian(self):
        bagi = self.angka01 / self.angka02
        print(bagi)

bilangan = Kalkulator(7,8)
bilangan.perkalian()
bilangan.penjumlahan()
bilangan.pembagian()